spring.application.name=Inventory

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=NEVER
spring.sql.init.platform=sqlite

spring.profiles.active=prod

app.db.meta.app-id=io.github.scrvrdn.Inventory
app.db.meta.schema-version=1